blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/kuraydev/react-native-bouncy-checkbox/discussions
    about: Ask usage questions and share ideas here.
